version: '2'

services:
    mongodb:
        build: ./.docker/mongodb
        volumes:
          - ./.docker/mongodb/data:/data/db
        ports:
          - "27017:27017"
    nginx:
        build: ./.docker/nginx
        volumes:
            - ./:/var/www/api
        links:
            - php
        ports:
            - "8080:80"
    php:
        build: ./.docker/php
        volumes:
            - ./:/var/www/api
        links:
            - mongodb